### ISSUE TITLE
Charset issue with postAjax iso-8859-1

### ISSUE THREAD

**Issue by sagoweb** [qcodo/qcodo#29]
Sending via ajax special characters like "è" when QApplication::$EncodingType is iso-8859-1 creates decodification problems in $_POST variable.
I think this is because all ajax request use utf-8 charset no matter what the encoding of the page is.
I tried adding a line in post.js after
objRequest.setRequestHeader("Content-Type", "application/x-www-form-urlencoded")
in order to force the right charset but with no success because setting accept-charset in webkit (I didn't tested more) it gives a security error.
So I ended up modifying this line in QTextBoxBase.class.php from:

$this->strText = $_POST[$this->strControlId];
to:
$this->strText = iconv("UTF-8",QApplication::$EncodingType, $_POST[$this->strControlId]);

This solved my problem. Maybe there is some better solution. I guess I should check if the request type is ajax or normal post as the browser automatically encodes post requests using page charset.

Thanks.

**Comment by mikeho** [comment]
I don't believe this is applicable anymore as QForms is no longer part of Qcodo, so closing.
