### ISSUE TITLE
Building _qc_packed.js

### ISSUE THREAD

**Issue by openbrian** [qcodo/qcodo#32]
What's the process of building _qc_packed.js?

**Comment by mikeho** [comment]
You can use any sort of JS packer or compiler tool.

For the official Qcodo builds I use the PHP version of the JavaScript Packer library (http://dean.edwards.name/packer/)

I concatenate the files in the following order:
* qcodo.js
* event.js
* logger.js
* post.js
* control.js

And then I add the contents of the rest of the .js files in www/assets/js/_core and run the contents thru JavaScript Packer.
